name: Validate

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate-hacs:
    runs-on: ubuntu-latest
    name: HACS Validation
    steps:
      - uses: actions/checkout@v4

      - name: HACS Action
        uses: hacs/action@main
        with:
          category: integration

  validate-hassfest:
    runs-on: ubuntu-latest
    name: Hassfest Validation
    steps:
      - uses: actions/checkout@v4

      - name: Hassfest
        uses: home-assistant/actions/hassfest@master
